CREATE TABLE books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  pages INT NOT NULL,
  genre VARCHAR(100) NOT NULL,
  lent_to VARCHAR(255) DEFAULT NULL,
  lent_date DATE DEFAULT NULL
);